/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.Fornecedor;
import controller.Produto;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.FornecedorDAO;
import model.ProdutosDAO;

/**
 *
 * @author HENRIQUE
 */
public class TelaPesquisaFornecedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaPesquiaProduto
     */
    public TelaPesquisaFornecedor() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) tblListaFornecedores.getModel();
        tblListaFornecedores.setRowSorter(new TableRowSorter(modelo));
    }

        //Isso é para carregar dados do banco na Tabela
    public void LerParaTabelaPorModelo(String modeloForn) throws SQLException {

        DefaultTableModel model = (DefaultTableModel) tblListaFornecedores.getModel();
        model.setNumRows(0);

        FornecedorDAO fDAO = new FornecedorDAO();
        
        for(Fornecedor forn : fDAO.bucaPorNFornecedor(modeloForn)){
            
            model.addRow(new Object[]{
            forn.getId_fornecedor(),
            forn.getNomeF(),
            forn.getEmailF(),
            forn.getTelefoneF(),
            
          
        });
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBotoes = new javax.swing.JPanel();
        t_bnomeF = new javax.swing.JLabel();
        c_BnomeF = new javax.swing.JTextField();
        btn_consultarF = new javax.swing.JButton();
        btn_limparF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlTabelaConsultaF = new javax.swing.JScrollPane();
        tblListaFornecedores = new javax.swing.JTable();
        c_telefoneF = new javax.swing.JTextField();
        t_telefone = new javax.swing.JLabel();
        c_emailF = new javax.swing.JTextField();
        t_email = new javax.swing.JLabel();
        c_nomeF = new javax.swing.JTextField();
        t_nome = new javax.swing.JLabel();
        btn_alterarF = new javax.swing.JButton();
        btn_excluirF = new javax.swing.JButton();
        t_idF = new javax.swing.JLabel();
        c_idF = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Pesquisa de Fornecedor");

        t_bnomeF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_bnomeF.setText("Buscar por nome:");

        btn_consultarF.setText("Consultar");
        btn_consultarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarFActionPerformed(evt);
            }
        });

        btn_limparF.setText("Limpar");
        btn_limparF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparFActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon.png"))); // NOI18N

        javax.swing.GroupLayout pnlBotoesLayout = new javax.swing.GroupLayout(pnlBotoes);
        pnlBotoes.setLayout(pnlBotoesLayout);
        pnlBotoesLayout.setHorizontalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t_bnomeF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_BnomeF, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_consultarF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_limparF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        pnlBotoesLayout.setVerticalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_bnomeF)
                    .addComponent(c_BnomeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_consultarF)
                    .addComponent(btn_limparF))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        tblListaFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Email", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListaFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaFornecedoresMouseClicked(evt);
            }
        });
        pnlTabelaConsultaF.setViewportView(tblListaFornecedores);

        c_telefoneF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_telefoneFActionPerformed(evt);
            }
        });

        t_telefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_telefone.setText("Telefone:");

        c_emailF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_emailFActionPerformed(evt);
            }
        });

        t_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_email.setText("Email:");

        c_nomeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nomeFActionPerformed(evt);
            }
        });

        t_nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_nome.setText("Nome:");

        btn_alterarF.setText("Alterar");
        btn_alterarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarFActionPerformed(evt);
            }
        });

        btn_excluirF.setText("Excluir");
        btn_excluirF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirFActionPerformed(evt);
            }
        });

        t_idF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_idF.setText("Código:");

        c_idF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_idFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTabelaConsultaF)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(btn_alterarF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(btn_excluirF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(t_email)
                                    .addComponent(t_nome))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(c_emailF)
                                    .addComponent(c_nomeF, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(t_telefone)
                                    .addComponent(t_idF))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c_idF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c_telefoneF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTabelaConsultaF, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t_telefone)
                        .addComponent(c_telefoneF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t_nome)
                        .addComponent(c_nomeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t_idF)
                        .addComponent(c_idF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t_email)
                        .addComponent(c_emailF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_alterarF)
                    .addComponent(btn_excluirF))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_consultarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarFActionPerformed
        try {
            LerParaTabelaPorModelo(c_BnomeF.getText());
        } catch (SQLException ex) {
        }  

    }//GEN-LAST:event_btn_consultarFActionPerformed

    
    private void btn_limparFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparFActionPerformed

        limparTelaPesquisaF(true);
    }//GEN-LAST:event_btn_limparFActionPerformed

    public void limparTelaPesquisaF(boolean limparTbl) {
        if (limparTbl){
            ((DefaultTableModel) tblListaFornecedores.getModel()).setRowCount(0);
            c_BnomeF.setText("");
            c_BnomeF.requestFocus();
            c_nomeF.setText("");
            c_emailF.setText("");
            c_telefoneF.setText("");
            c_idF.setText("");
        }else{
            c_BnomeF.setText("");
            c_BnomeF.requestFocus();
            c_nomeF.setText("");
            c_emailF.setText("");
            c_telefoneF.setText("");
            c_idF.setText("");
        }
        
        

    }
    
    
    private void c_telefoneFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_telefoneFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_telefoneFActionPerformed

    private void c_emailFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_emailFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_emailFActionPerformed

    private void c_nomeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nomeFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nomeFActionPerformed

    private void btn_alterarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarFActionPerformed
        alterarFornecedor();
        
        try {
            
            LerParaTabelaPorModelo(c_nomeF.getText());
            limparTelaPesquisaF(false);
        } catch (SQLException ex) {
        } 
    }//GEN-LAST:event_btn_alterarFActionPerformed
    
    private void alterarFornecedor(){
               try{
           Fornecedor fornA = new Fornecedor();
            
            int id_fornecedorA;
            String nomeFA, emailA, telefoneA;
            
            id_fornecedorA = Integer.parseInt(c_idF.getText());
            nomeFA = c_nomeF.getText();
            emailA = c_emailF.getText();
            telefoneA = c_telefoneF.getText();
            
            fornA.setId_fornecedor(id_fornecedorA);
            fornA.setNomeF(nomeFA);
            fornA.setEmailF(emailA);
            fornA.setTelefone(telefoneA);
            
            FornecedorDAO fdao = new FornecedorDAO();
            
            fdao.alterarFornecedor(fornA);
            
            JOptionPane.showMessageDialog(null, "Fornecedor alterado com sucesso!");
            
       }catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Erro ao alterar!");
            System.out.println(e.getMessage());
        }
    }
    
    private void excluirFornecedor(){
        try{
            
            int id_fornecedorE;
            
            id_fornecedorE = Integer.parseInt(c_idF.getText());
            
            Fornecedor fornE = new Fornecedor();
            fornE.setId_fornecedor(id_fornecedorE);
            
            FornecedorDAO fdao = new FornecedorDAO();
            fdao.excluirFornecedor(fornE);
            
            JOptionPane.showMessageDialog(null, "Fornecedor excluido com sucesso!");
        }catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Erro ao excluit!");
            System.out.println(e.getMessage());
        }
        
    }
    private void tblListaFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaFornecedoresMouseClicked
    int setar = tblListaFornecedores.getSelectedRow();
        
        c_idF.setText(tblListaFornecedores.getModel().getValueAt(setar, 0).toString());
        c_nomeF.setText(tblListaFornecedores.getModel().getValueAt(setar, 1).toString());
        c_emailF.setText(tblListaFornecedores.getModel().getValueAt(setar, 2).toString());
        c_telefoneF.setText(tblListaFornecedores.getModel().getValueAt(setar, 3).toString());
        c_idF.setEnabled(false);
        
        
    }//GEN-LAST:event_tblListaFornecedoresMouseClicked

    private void c_idFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_idFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_idFActionPerformed

    private void btn_excluirFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirFActionPerformed
        int op = JOptionPane.showInternalConfirmDialog(null, "Deseja excluir o fornecedor? \n"
                + "Obs: Isso apagará todos os produtos desse fornecedor.", "Excluir Fornecedor", 
                JOptionPane.YES_NO_OPTION);
        
        if (op == JOptionPane.YES_OPTION){
            excluirFornecedor();
            limparTelaPesquisaF(true);
        }
        
        
    }//GEN-LAST:event_btn_excluirFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterarF;
    private javax.swing.JButton btn_consultarF;
    private javax.swing.JButton btn_excluirF;
    private javax.swing.JButton btn_limparF;
    private javax.swing.JTextField c_BnomeF;
    private javax.swing.JTextField c_emailF;
    private javax.swing.JTextField c_idF;
    private javax.swing.JTextField c_nomeF;
    private javax.swing.JTextField c_telefoneF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JScrollPane pnlTabelaConsultaF;
    private javax.swing.JLabel t_bnomeF;
    private javax.swing.JLabel t_email;
    private javax.swing.JLabel t_idF;
    private javax.swing.JLabel t_nome;
    private javax.swing.JLabel t_telefone;
    private javax.swing.JTable tblListaFornecedores;
    // End of variables declaration//GEN-END:variables
}
