/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.Fornecedor;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import model.FornecedorDAO;

/**
 *
 * @author HENRIQUE
 */
public class TelaC_Fornecedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaC_Fornecedor
     */
    public TelaC_Fornecedor() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_novoF = new javax.swing.JButton();
        c_emailF = new javax.swing.JTextField();
        c_telefoneF = new javax.swing.JTextField();
        c_nomeF = new javax.swing.JTextField();
        t_email = new javax.swing.JLabel();
        t_telefone = new javax.swing.JLabel();
        t_nome = new javax.swing.JLabel();
        t_cadastroF = new javax.swing.JLabel();
        btn_cancelarF = new javax.swing.JButton();
        btn_salvarF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Forncedor");

        btn_novoF.setText("Novo");
        btn_novoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoFActionPerformed(evt);
            }
        });

        c_emailF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_emailFActionPerformed(evt);
            }
        });

        c_telefoneF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_telefoneFActionPerformed(evt);
            }
        });

        c_nomeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nomeFActionPerformed(evt);
            }
        });

        t_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_email.setText("Email:");

        t_telefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_telefone.setText("Telefone:");

        t_nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_nome.setText("Nome:");

        t_cadastroF.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        t_cadastroF.setText("Cadastro de Fornecedor");

        btn_cancelarF.setText("Cancelar");
        btn_cancelarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarFActionPerformed(evt);
            }
        });

        btn_salvarF.setText("Salvar");
        btn_salvarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarFActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(t_email)
                                    .addComponent(t_nome)
                                    .addComponent(t_telefone))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(c_emailF)
                                    .addComponent(c_nomeF, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btn_salvarF)
                                        .addComponent(c_telefoneF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(btn_novoF)
                                .addGap(243, 243, 243)
                                .addComponent(btn_cancelarF)))
                        .addGap(0, 92, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_cadastroF)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t_cadastroF)
                    .addComponent(jLabel1))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_nome)
                    .addComponent(c_nomeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_email)
                    .addComponent(c_emailF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_telefone)
                    .addComponent(c_telefoneF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_novoF)
                    .addComponent(btn_salvarF)
                    .addComponent(btn_cancelarF))
                .addGap(34, 34, 34))
        );

        setBounds(0, 0, 600, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarFActionPerformed
        dispose();
    }//GEN-LAST:event_btn_cancelarFActionPerformed

    private void btn_novoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoFActionPerformed
        limparTelaCadastroF();
    }//GEN-LAST:event_btn_novoFActionPerformed

    private void btn_salvarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarFActionPerformed
        Fornecedor forn = new Fornecedor();

        try {
            String nomeF;
            String email;
            String telefone;

            //validacao de campo fazer mais verificação
            if (c_nomeF.getText().length() < 1) {
                JOptionPane.showMessageDialog(null, "Prencha o campo Nome");
                c_nomeF.requestFocus();
            } else if (c_emailF.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Prencha o campo Email");
                c_emailF.requestFocus();
            } else if (c_telefoneF.getText().length() < 1) {
                JOptionPane.showMessageDialog(null, "Prencha o campo telefone");
                c_telefoneF.requestFocus();
            } else {
                nomeF = c_nomeF.getText();
                email = c_emailF.getText();
                telefone = c_telefoneF.getText();

                forn.setNomeF(nomeF);
                forn.setEmailF(email);
                forn.setTelefone(telefone);

                FornecedorDAO fd = new FornecedorDAO();
                fd.insereFornecedor(forn);

                JOptionPane.showMessageDialog(null, "Fornecedor cadastrado com sucesso");

                limparTelaCadastroF();
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_salvarFActionPerformed

    private void c_emailFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_emailFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_emailFActionPerformed

    private void c_nomeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nomeFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nomeFActionPerformed

    private void c_telefoneFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_telefoneFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_telefoneFActionPerformed

    public void limparTelaCadastroF() {
        //limpando campos
        c_nomeF.setText("");
        c_emailF.setText("");
        c_telefoneF.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelarF;
    private javax.swing.JButton btn_novoF;
    private javax.swing.JButton btn_salvarF;
    private javax.swing.JTextField c_emailF;
    private javax.swing.JTextField c_nomeF;
    private javax.swing.JTextField c_telefoneF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel t_cadastroF;
    private javax.swing.JLabel t_email;
    private javax.swing.JLabel t_nome;
    private javax.swing.JLabel t_telefone;
    // End of variables declaration//GEN-END:variables
}
